### ISSUE TITLE
Background image doesn't change

### ISSUE THREAD

**Issue by theniwo** [wtheisen/BashDynamicPaper#1]
Hi, I am running ubuntu-studio 18.04 with xfce.
The command runs without error, but the background doesn't change.
When I logoff, however, I see the changed background when the DE is shutting down. When the login screen is loaded, the default wallpaper is applied.
It looks like feh is unable to overwrite the wallpaper settings from xfce
I changed the feh command to an `xfconf-query' command. Look at my fork. Maybe you can include that code and check for the desktop env in the script ;-)

**Comment by wtheisen** [comment]
Is this when you run it as a cronjob or directly in the terminal?

**Comment by wtheisen** [comment]
Okay I'll take a look, I'm happy to approve any PRs that will increase the functionality!

**Comment by wtheisen** [comment]
So if you run the script, and then run `xfdesktop --reload` would the wallpaper change?

**Comment by theniwo** [comment]
> xfdesktop --reload

No I get an error. `Gtk-Message: 14:32:38.162: Failed to load module "atk-bridge"`

**Comment by wtheisen** [comment]
Okay I've made quite a few changes to the code since you forked, but if you pull the newest version it should be relatively easy for you to just slot your code into another `which xconf-query` block in `set_pape()`. Conversely if you're not interested in the PR I'm happy to add it to the code myself.

**Comment by theniwo** [comment]
I made a pull request and I will work from there.
